---
label: Action
is_partial: true
display_field: label
fields:
  - type: text
    name: label
    label: Label
  - type: text
    name: url
    label: URL
  - type: boolean
    name: is_scrolly
    label: IS Scrolly
    default: false
  - type: boolean
    name: is_primary
    label: Is Primary
    default: false
